### ISSUE TITLE
Unable to download videos from instagram if the post has a photo attached too.

### ISSUE THREAD

**Issue by Xerbeous** [imputnet/cobalt#609] opened 2024-07-04 03:02 UTC
Instagram posts that have a video and a photo don't allow you to download the video and shows up as "i don't see anything i could download by your link. try a different one!"

### screenshots
![image](https://github.com/imputnet/cobalt/assets/174671818/77fbaa06-d9ba-47fa-9229-55f62c6f6e02)

### platform information
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]

### additional context
Instagram posts that are only a video can be downloaded but the ones that have a video and a photo attached, the video can't be downloaded

**Comment by wukko** [comment] 2024-07-04 03:04
duplicate of #572

**Closed by wukko** 2024-07-04 03:04 UTC
Labels: duplicate
