### ISSUE TITLE
YouTube Clip downloading support

### ISSUE THREAD

**Issue by YTR76** [imputnet/cobalt#388] opened 2024-03-10 06:25 UTC
**describe the feature you'd like to see**
youtube clip support

**describe alternatives you've considered**
y2down, but i wouldn't really recommend that because it has the problem that cobalt is supposed to solve
 
**additional context**
that's it tbh

**Comment by lostdusty** [comment] 2024-03-10 14:49
Already in the works, see #350.

**Comment by protectedprofile** [comment] 2024-03-11 20:48
A lot of mp3's I want on music.youtube.com can't be downloaded due to restriction, can only be streamed. I wish this could be solved. Try the artist Dio and share my frustration.

**Comment by PoketrainerMS** [comment] 2024-07-16 22:12
in the meantime, id recommend the Discord bot MediaForge, though it's not always online sadly

**Comment by wclxb** [comment] 2024-09-20 22:57
> Already in the works, see #350.

This would be different than downloading a YouTube clip. The request is support for downloading "youtube.com/clip/CLIP_ID" urls.

**Comment by dumbmoron** [comment] 2024-09-20 23:25
duplicate of #128

**Closed by dumbmoron** 2024-09-20 23:25 UTC
Labels: feature request
