### ISSUE TITLE
New API: /api/url

### ISSUE THREAD

**Issue by SmilerRyan** [imputnet/cobalt#708] opened 2024-09-01 21:42 UTC
### New API: /api/url
Currently when using the json API, you have to send a POST request, parse the json response, then return the url from the json response. I would like to be able to directly send a GET request to the API and get redirected to the url, for cases where you need a direct URL to the file such as Discord bots etc.

### Additional Context
For compatibility of other things that use direct links (such as Discord bots etc), this needs to be supported.
I would like to be able to use it like this example, but anything else is appreciated as well:

https://api.cobalt.tools/api/url?aFormat=best&isAudioOnly=true&url=https://youtu.be/wcT7zgL6gug

![image](https://github.com/user-attachments/assets/fb91b385-4b45-4ea9-87d9-730e782967af)

**Comment by lostdusty** [comment] 2024-09-01 22:50
i dont think thats a good design

**Comment by KwiatekMiki** [comment] 2024-09-01 22:51
why did you make 2 issues related to 1 thing

**Comment by SmilerRyan** [comment] 2024-09-01 23:03
> why did you make 2 issues related to 1 thing

I posted 2 issues since whilst both feel like they are needed for me, they are both different things.
One being to accept GET parameters instead of just POST parameters, and the other to have an endpoint that redirects to a video.


> i dont think thats a good design

How would prefer to do this?
My initial thought before deciding on a different endpoint was an extra json such as ``"redirectToUrl": true``.
If it exists to redirect instead of showing the json, but it feels more right to have a different endpoint to expect a url rather than json (url only at ``/api/url`` instead of ``/api/json`` so it's less misleading).

**Comment by wukko** [comment] 2024-09-02 00:44
duplicate of #707, see my reply there

**Closed by wukko** 2024-09-02 00:44 UTC
Labels: feature request
