### ISSUE TITLE
Spinner won't disappear

### ISSUE THREAD

**Issue by prettyDave89** [imputnet/cobalt#873] opened 2024-10-31 04:53 UTC
### bug description

Spinner won't disappear allowing me to use the site. A message pops up that says to reach out to you guys if this happens as i'm likely blocked for some weird reason.

Message: still checking if you're not a bot. wait for the spinner to disappear and try again.
if it takes too long, please let us know! we use cloudflare turnstile for bot protection and sometimes it blocks people for no reason.

### reproduction steps

1. go to: https://cobalt.tools/
2. input desired video URL in the command bar
3. click the download icon
4. get pop up with message included in bug description

### platform information

Windows 11 Pro, Chrome Version 130.0.6723.70 (Official Build) (64-bit)

**Comment by wukko** [comment] 2024-11-10 04:27
duplicate of #811

**Closed by wukko** 2024-11-10 04:27 UTC
Labels: main instance issue
