### ISSUE TITLE
request: facebook

### ISSUE THREAD

**Issue by MrRorls12** [imputnet/cobalt#516] opened 2024-05-23 00:08 UTC
**describe the feature you'd like to see**
i want to be able to download facebook videos

**describe alternatives you've considered**
using that ezdailymotion site _(shudder)_

**additional context**
don't have any :P

**Comment by wukko** [comment] 2024-05-23 02:46
duplicate of #54

**Closed by wukko** 2024-05-23 02:46 UTC
Labels: feature request

**Comment by MrRorls12** [comment] 2024-05-24 00:40
:( sorry

**Comment by wukko** [comment] 2024-05-24 03:35
it's okay, don't apologize for nothing
