### ISSUE TITLE
Multiple songs from 1 Specific album aren't downloadable (i can't access this video. it may be restricted on youtube's side. try a different link!)

### ISSUE THREAD

**Issue by Chidubemmo** [imputnet/cobalt#968] opened 2024-11-28 20:40 UTC
### bug description

This error seems to happen only with the Chromakopia Album by Tyler, the Creator.
No song is downloadable.
This doesn't happens for example with the Kendrick's GNX album which is newer

### reproduction steps

1. Get the link of any song from the Chromakopia album
2. Paste it on cobalt

### screenshots

![image](https://github.com/user-attachments/assets/00856440-14e0-4440-a376-dc9a07b1081b)
![{77A4C0CC-3425-4322-86D3-218B9C647EB5}](https://github.com/user-attachments/assets/6a362089-2bb3-4183-89cb-9b9fb63da225)

![image](https://github.com/user-attachments/assets/1534d3b6-97c3-485c-abfe-41bd075cef4e)

### links

```shell
https://www.youtube.com/watch?v=R_clisSImS4
https://www.youtube.com/watch?v=16KSivdIGjQ
```

### platform information

Windows 11 on Firefox 133.0 (64 bit)

**Comment by TommyTonka** [comment] 2024-11-28 22:34
this is why i'm gonna move on to JDownloader, because of "restricted on youtube's side" and because Cobalt is becoming useless

**Comment by wukko** [comment] 2024-11-29 02:43
duplicate of #961 

> i'm gonna move on to JDownloader

farewell!

**Closed by wukko** 2024-11-29 02:43 UTC
Labels: main instance issue

**Comment by TommyTonka** [comment] 2024-11-29 16:26
I'm sorry Wukko but I had to say it

**Comment by KwiatekMiki** [comment] 2024-11-29 16:37
> I'm sorry Wukko but I had to say it

you didn't have to, no one was forcing you to say it
