### ISSUE TITLE
Cobalt never stops checking if I´m a bot

### ISSUE THREAD

**Issue by Ushikawa899** [imputnet/cobalt#864] opened 2024-10-25 19:45 UTC
### bug description

That´s pretty much it, I don´t know why but the wheel never stops spinning (ouroborosjoke) and I can´t paste anything

### reproduction steps

I have no idea teach me how  to code!!!! kidding

### screenshots

![image](https://github.com/user-attachments/assets/4cf246a3-1829-4dde-b51b-13f97e17feeb)

### platform information

windows 10

**Comment by wukko** [comment] 2024-11-10 04:26
duplicate of #811

**Closed by wukko** 2024-11-10 04:26 UTC
Labels: bug
