### ISSUE TITLE
he site isn't working properly.

### ISSUE THREAD

**Issue by caohuan99** [imputnet/cobalt#993] opened 2024-12-12 04:54 UTC
### bug description

I can't download files for the past two days, and all the files I download are 0 bytes. Is it because of youtube's restrictions?

### reproduction steps

macOS 10.13

### screenshots

<img width="310" alt="屏幕快照 2024-12-12 下午12 47 02" src="https://github.com/user-attachments/assets/4dd41bb6-bfc0-461d-b74e-f6f5a7a111ef" />

### platform information

chrome 116.0.5845.187 on macOS 10.13

**Comment by hamidb80** [comment] 2024-12-12 07:46
same as https://github.com/imputnet/cobalt/issues/992

**Comment by wukko** [comment] 2024-12-12 07:56
duplicate of #992

**Closed by wukko** 2024-12-12 07:56 UTC
Labels: main instance issue
