### ISSUE TITLE
Can't run cobalt api in regions where YouTube is blocked

### ISSUE THREAD

**Issue by majianming21** [imputnet/cobalt#521] opened 2024-05-24 14:00 UTC
i first run [docker-compose.example.yml](https://github.com/imputnet/cobalt/blob/current/docs/examples/docker-compose.example.yml) as a stack and get some error 

![图片](https://github.com/imputnet/cobalt/assets/18475632/6ca00c08-f9cd-4324-be7a-06841a6e35ff)

**env**
my version is latest,from ghcr.io/imputnet/cobalt:7.14.2-5c11e57

what should i do?

**Comment by wukko** [comment] 2024-05-24 14:35
does the container have internet access?

**Comment by majianming21** [comment] 2024-05-24 15:00
yes , i have internet for container, some time can have remote site ip 
![图片](https://github.com/imputnet/cobalt/assets/18475632/1a3223f9-7bea-4862-b89f-c322c880f406)
****

**Comment by majianming21** [comment] 2024-05-24 15:11
![图片](https://github.com/imputnet/cobalt/assets/18475632/17e41fde-9e50-4408-92ee-55d1207e5eff)

i location chinese mainland and can not access some website as google  directly.

**Comment by wukko** [comment] 2024-05-28 03:56
the error is caused by cobalt fetching youtube session on boot. since youtube api is unreachable, an error is thrown. fix should include making youtube session fetching async & optional if it fails.

you have to wait for us to make a fix for this, but i'll comment one more time once it's done!

**Closed** 2024-05-29 08:26 UTC
Labels: bug
