### ISSUE TITLE
Instagram download not working

### ISSUE THREAD

**Issue by bajun** [imputnet/cobalt#800] opened 2024-10-03 21:11 UTC
### bug description

Hi! 
When I'm trying to download reels from Instagram (either from my instance or from yours), it shows an error - 
`{
    "status": "error",
    "error": {
        "code": "error.api.fetch.fail",
        "context": {
            "service": "instagram"
        }
    }
}`

### reproduction steps

1. Go to https://cobalt.tools/
2. Submit reels url

### screenshots

![image](https://github.com/user-attachments/assets/59c1bebb-359c-47be-82e4-4b393c72357f)

### links

```shell
https://www.instagram.com/reel/CreL631gOl3
```

### platform information

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

### additional context

`{
  "is": {
    "iPhone": false,
    "iPad": false,
    "iOS": false,
    "android": false,
    "mobile": false
  },
  "prefers": {
    "language": "uk",
    "reducedMotion": false,
    "reducedTransparency": false
  },
  "supports": {
    "share": true,
    "directDownload": true
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
}

{
  "schemaVersion": 2,
  "appearance": {
    "theme": "dark"
  },
  "privacy": {},
  "save": {
    "youtubeVideoCodec": "h264",
    "videoQuality": "720",
    "audioFormat": "mp3",
    "downloadMode": "auto",
    "filenameStyle": "classic"
  },
  "processing": {
    "enableCustomInstances": false
  },
  "advanced": {
    "debug": true
  }
}

{
  "commit": "e419de07a43270db2a43c89f9215088e5d489d8b",
  "branch": "main",
  "remote": "imputnet/cobalt",
  "version": "10.1.0"
}
`

**Comment by steazzy** [comment] 2024-10-05 14:43
reels works for me. https://www.instagram.com/pirat_serega/reel/C20ctLLxdhA/ But photos doesn't

**Comment by wukko** [comment] 2024-10-16 16:53
duplicate of #539

**Closed by wukko** 2024-10-16 16:53 UTC
Labels: duplicate
