### ISSUE TITLE
Downloading specific timestamp sections from a video

### ISSUE THREAD

**Issue by RubynRuby** [imputnet/cobalt#528] opened 2024-05-28 07:08 UTC
**describe the feature you'd like to see**
the ability to input a start time stamp and an end timestamp and then download that specific section of the video instead of the whole video

**describe alternatives you've considered**
there are websites that claim such feature but non of them is working

**Comment by dumbmoron** [comment] 2024-05-28 07:09
duplicate of #375

**Closed by dumbmoron** 2024-05-28 07:09 UTC
Labels: feature request
