### ISSUE TITLE
[short feature request description] request to support instagram stories

### ISSUE THREAD

**Issue by adhame95** [imputnet/cobalt#705] opened 2024-09-01 06:51 UTC
### describe the feature you'd like to see
clear and concise description of the feature you want to see in cobalt.

Could you support downloading of instagram stories?

here is a link https://www.instagram.com/s/aGlnaGxpZ2h0OjE4NDU0OTQ0OTg1MDU3NzQ5?story_media_id=2238022832873491356&igsh=MTJsdXBiNmw3OXM5cQ==

**Comment by KwiatekMiki** [comment] 2024-09-01 09:20
They are supported (#194), but highlight are not (after clicking on your link it took me to a highlight), so this is a duplicate of #399.

**Closed** 2024-09-02 00:44 UTC
Labels: feature request
