### ISSUE TITLE
Instagram download is down

### ISSUE THREAD

**Issue by aimen08** [imputnet/cobalt#580] opened 2024-06-20 07:12 UTC
**bug description**
Instagram download is down.

**reproduction steps**
steps to reproduce the behavior:
1.  download any video from Instagram

**screenshots**
<img width="1174" alt="image" src="https://github.com/imputnet/cobalt/assets/32209952/a672ed07-680f-4f7a-a9b4-5e0fb1b58ccd">

**platform**
- website
- self-hosting

**Comment by ihatespawn** [comment] 2024-06-27 15:58
only affects the main instance, try another instance
https://instances.hyper.lol

**Comment by wukko** [comment] 2024-06-27 16:03
> only affects the main instance

nope, it's a global issue that affects any instances with either big enough traffic or datacenter ips. it's an unfixable issue atm

**Comment by aimen08** [comment] 2024-06-27 22:21
Hey @wukko i want to help fix this issue , just before i start i'm studying the code of Instagram module, this is how it's setup right ? 

```mermaid
graph TD
    A[Start: Module called with object] --> B{Check input}
    B -->|postId present| C[Call getPost]
    B -->|username and storyId present| D[Call getStory]
    B -->|Neither condition met| E[Return ErrorUnsupported]

    C --> F[Attempt to fetch post data]
    F --> G{Data fetched successfully?}
    G -->|Yes| H[Extract post data]
    G -->|No| I[Return ErrorCouldntFetch]
    H --> J[Return post data]

    D --> K[Convert username to userId]
    K --> L[Fetch story data]
    L --> M{Story data found?}
    M -->|Yes| N[Extract story data]
    M -->|No| O[Return ErrorEmptyDownload]
    N --> P[Return story data]

    subgraph "getPost function"
    F --> F1[Try mobile API with token]
    F1 --> F2[Try mobile API without token]
    F2 --> F3[Try HTML embed]
    F3 --> F4[Try web app GraphQL API]
    end

    subgraph "Data extraction"
    H --> H1{Is it an old or new post format?}
    H1 -->|Old| H2[Extract using extractOldPost]
    H1 -->|New| H3[Extract using extractNewPost]
    end
```

**Comment by dumbmoron** [comment] 2024-06-27 22:23
> i want to help fix this issue , just before i start i'm studying the code of Instagram module, this is how it's setup right ?
@aimen08 looks about right to me, except "Return post data" comes after extractOld/NewPost

**Comment by wukko** [comment] 2024-06-29 12:47
duplicate of #572

**Closed by wukko** 2024-06-29 12:47 UTC
Labels: duplicate
