### ISSUE TITLE
support for videos from niconico douga (nicovideo)

### ISSUE THREAD

**Issue by lalondeguy** [imputnet/cobalt#552] opened 2024-06-07 12:05 UTC
**describe the feature you'd like to see**
title, would like to be able to download videos from niconico douga.

**describe alternatives you've considered**
afaik there aren't any other sites that let you download videos from it, so... none? (idk though)

**additional context**
idk about anyone else, but the site is pretty important to the vocaloid community as a lot of vocaloid songs are only posted there, being able to easily download videos from it would help a lot with preserving and reprinting them

**Comment by dumbmoron** [comment] 2024-06-07 12:21
duplicate of #60, pending pull request: #510

**Closed by dumbmoron** 2024-06-07 12:21 UTC
Labels: feature request
