### ISSUE TITLE
[short feature request description]

### ISSUE THREAD

**Issue by HansGeo** [imputnet/cobalt#630] opened 2024-07-12 17:19 UTC
### Add Subtitles Support

Hi,

I just tried cobalt to download some yt videos and it works impressingly simple and fast. 
Thank you for providing the service. :))
What about **adding a feature to download subtitles?**
Having subtitles on, facilitates listening to lengthy video-talks.
I myself am not into coding. So I have to rely on cobalt coders.

Hope you think it over.
Thank you
 
best whishes
Hans

**Comment by ihatespawn** [comment] 2024-07-12 17:34
[short response related to the issue]

**Comment by ihatespawn** [comment] 2024-07-12 17:34
okay but actually this is a duplicate of #368

**Closed** 2024-07-12 18:09 UTC
Labels: feature request
