### ISSUE TITLE
YouTube Playlists

### ISSUE THREAD

**Issue by voidxO7** [imputnet/cobalt#757] opened 2024-09-17 06:43 UTC
### describe the feature you'd like to see

I would like to able to insert a link into Cobalt and get a zip file containing the files for the playlist.

### additional context

If this couldn’t be done with YouTube.js or whatnot, a potential solution to it would be to write a script that takes the individual links then downloads and zips them all together.

**Comment by KwiatekMiki** [comment] 2024-09-17 15:39
duplicate of #193

**Closed** 2024-09-18 04:10 UTC
Labels: feature request
