### ISSUE TITLE
Youtube media got cut to ramdom legth

### ISSUE THREAD

**Issue by shawnchiao** [imputnet/cobalt#725] opened 2024-09-10 04:16 UTC
### bug description

I found when the video is longer than ( 45 mins or more) it will not get me download the full legth of the media file.
I tried one with 1h:50m and the other 2h:50m. They will be cut to around 3x mins to 4x mins.
I am not sure this is know issue or new one... as I just new to combalt using

### reproduction steps

1. go to https://cobalt.tools/
2. pase a youtube url that is longer than 45mins
3. press download and checkout the length of downloaded files

### platform information

mac

**Comment by Sirocco745** [comment] 2024-09-10 04:42
This is a recurrent issue the devs are aware of, they've even pinned an issue related to exactly this at the top of the issues page (https://github.com/imputnet/cobalt/issues/647). Give 'em time, things will get sorted out eventually :D

**Comment by KwiatekMiki** [comment] 2024-09-10 06:50
duplicate of #647

**Closed** 2024-09-16 05:16 UTC
Labels: main instance issue
