### ISSUE TITLE
Add NicoNico support links

### ISSUE THREAD

**Issue by BentleyBentayga** [imputnet/cobalt#699] opened 2024-08-29 03:41 UTC
### describe the feature you'd like to see
I'm trying to download my NicoNico covers to MP3 and tried multiple sites involving the converter but to no avail. Would it be useful enough for those who want to easily convert any NicoNico video into any format if this added a new feature for NicoNico support links?

**Comment by KwiatekMiki** [comment] 2024-08-29 07:25
duplicate of #60

**Closed** 2024-08-29 07:27 UTC
Labels: feature request
