### ISSUE TITLE
Youtube Link Download Error

### ISSUE THREAD

**Issue by OneBearo** [imputnet/cobalt#972] opened 2024-12-01 00:24 UTC
### bug description

I've looked through other issues and it seems like this issue has happened before- Whenever I try and download any video, I end up getting an error message saying, "i can't access this video. it may be restricted on youtube's side. try a different link!" Other devices I use seem to have the same issue, including when the wifi is off.

### reproduction steps

1. copy youtube link from the search bar
2. go to cobalt
3. paste in the link (using the auto mode)
4. get error message :(

### screenshots

![image](https://github.com/user-attachments/assets/b4e8a50b-ab5e-450c-9bf0-2201ac743174)

### platform information

Windows 11, Edge 131

**Comment by MagesticChicen** [comment] 2024-12-01 00:37
I have had this problem for the last 3-5 days roughly and can second it's existence. 

Can't download any of my music anymore. I've tried links on all formats of the YouTube TLD, including YouTube music, standard YouTube and w/YouTube links excluding share IDs or shorteners.

**Comment by andorrra** [comment] 2024-12-01 02:47
i can third its existence as i have not been able to download the auto-generated reuploads of songs ripped from spotify or wherever. some music videos don't even work either even though i can access all of these things normally on youtube. this has been a thing since november 25th for me at least

**Comment by wukko** [comment] 2024-12-01 04:27
duplicate of #961 

next time fill out the “links” section of the issue

**Closed by wukko** 2024-12-01 04:27 UTC
Labels: main instance issue
