### ISSUE TITLE
YouTube download again not working

### ISSUE THREAD

**Issue by demiiyou** [imputnet/cobalt#967] opened 2024-11-28 15:51 UTC
### bug description

Probably the dummies again.
When trying to download YouTube video, Cobalt answers with "Can't access this video...".

### reproduction steps

1.Go to YouTube
2.Copy Video Link
3.Paste Video Link in Cobalt
4. Error message when trying to download

### platform information

Google Chrome newest version

**Comment by wukko** [comment] 2024-11-28 15:55
https://www.youtube.com/watch?v=dQw4w9WgXcQ works fine to me. since you haven't filled out any of the required sections for issue reproduction, i'm closing this issue.

**Closed by wukko** 2024-11-28 15:55 UTC
Labels: main instance issue
